{% set version = "0.3.7" %}

package:
  name: jp-noui
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jp_noui/jp_noui-{{ version }}.tar.gz
  sha256: ba9fb29c8a03b7148ce03b3b580e7dae20073f42ff21ffc65bd32a92d5dc7246

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - "jupyter-noui = jp_noui.app:main"

requirements:
  host:
    - hatch-jupyter-builder
    - jupyterlab >=3,<4
    - pip
    - python >=3.7

  run:
    - python >=3.7

  run_constrained:
    - jupyterlab >=3,<4

test:
  requires:
    - pip
    - jupyterlab >=3,<4
    - m2-grep  # [win]
  imports:
    - jp_noui
  commands:
    - pip check
    - jupyter labextension list 2>&1 | grep -iE "jp-noui.*v{{ version }}.*OK"
    - jupyter noui --version 2>&1 | grep -iE "{{ version }}"
    - jupyter noui --help 2>&1 | grep -iE "jupyter noui --config=my_config.json"

about:
  home: https://github.com/JoelStansbury/jp-noui
  summary: Hides jupyterlab UI elements for presentable notebook applications
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - {{ PREFIX }}/share/jupyter/labextensions/jp-noui/static/third-party-licenses.json


extra:
  recipe-maintainers:
    - JoelStansbury
